### ISSUE TITLE
[Enhancement]Adding TOC for all widths ?

### ISSUE THREAD

**Issue by siddharthst** [taikii/whiteplain#19]
Awesome theme!
But I have encountered a problem, which can be considered more like an enhancement. Currently, the theme omits TOC for devices like cell phones. Is there a way to enable it regardless of the display width?

**Comment by taikii** [comment]
@siddharthst Thanks for your suggestion!
This theme has no option to display TOC on mobile.
But, you can make your wishes come true by making custom CSS like below.

File: `{your blog root}/static/css/custom.css`

```css
@media screen and (max-width: 768px) {
  .toc {
    display: block;
    float: none;
    width: 100%;
    box-sizing: border-box;
    margin: 0px;
  }
}
```
