### ISSUE TITLE
can not use categories page

### ISSUE THREAD

**Issue by Luosuu** [taikii/whiteplain#26]
I add `categories=["type"]`in my front matter, it's in toml
it looks like:
```toml
+++
author= "luosuu"
title= "title"
date= 2019-11-12T10:30:46+08:00
discription=""
categoires=["notes"]
weight=1
tags=["some tags"]
toc=true
+++
```
but in categories page there is nothing.
I don't konw whether I should change something in congfig.toml or should add a html file somewhere.Thanks you
